const DATA_URL='data/area_a_parcels.geojson', BOUNDARY_URL='data/area_a_boundary.geojson';
let map, parcelsLayer, boundaryLayer, features=[], selected=null, supa=null, channel=null, demo=false;
const state=new Map();
const $=id=>document.getElementById(id);
function toast(msg){$('toast').textContent=msg; $('toast').style.cssText='position:fixed;z-index:4000;left:50%;bottom:25px;transform:translateX(-50%);background:#111827;color:#fff;padding:10px 14px;border-radius:9px;box-shadow:0 4px 20px #0004'; setTimeout(()=>$('toast').style.cssText='',2400)}
function key(){return 'areaA_canvass_demo'}
function loadDemo(){try{const x=JSON.parse(localStorage.getItem(key())||'{}');Object.entries(x).forEach(([k,v])=>state.set(k,v))}catch{}}
function saveDemo(){localStorage.setItem(key(),JSON.stringify(Object.fromEntries(state)))}
function statusFor(id){return state.get(id)||{status:'unvisited'}}
function styleFeature(f){const s=statusFor(f.properties.ParcelID); return {className:'parcel '+s.status, color:s.status==='visited'?'#166534':s.status==='claimed'?'#b45309':'#374151', fillColor:s.status==='visited'?'#22c55e':s.status==='claimed'?'#f59e0b':'#fff', fillOpacity:s.status==='visited'?.65:s.status==='claimed'?.45:.22, weight:1};}
function updateStats(){let v=0,c=0; state.forEach(s=>{if(s.status==='visited')v++; else if(s.status==='claimed')c++}); $('visited').textContent=v; $('claimed').textContent=c; $('remaining').textContent=features.length-v-c; $('count').textContent=features.length.toLocaleString()+' parcels';}
function refresh(){if(parcelsLayer)parcelsLayer.eachLayer(l=>l.setStyle(styleFeature(l.feature)));updateStats()}
function user(){return $('userName').value.trim()||localStorage.getItem('canvass_name')||''}
$('userName').addEventListener('change',()=>localStorage.setItem('canvass_name',$('userName').value.trim()));
async function setStatus(id,status){const name=user();if(!name){toast('Enter your name first');return} const old=statusFor(id); if(status==='claimed' && old.status==='claimed' && old.user!==name){toast('Already claimed by '+old.user);return} if(status==='visited'){if(old.status==='claimed'&&old.user!==name){toast('This parcel is claimed by '+old.user);return}}
 const row={status,user:name,updated_at:new Date().toISOString()};
 if(demo){state.set(id,row);saveDemo();refresh();openSelected();return}
 const {error}=await supa.from('canvass_status').upsert({parcel_id:id,...row},{onConflict:'parcel_id'}); if(error){toast(error.message);return} state.set(id,row);refresh();openSelected();}
async function release(id){const old=statusFor(id),name=user();if(old.user&&old.user!==name){toast('Only '+old.user+' can release this parcel');return} if(demo){state.delete(id);saveDemo();refresh();openSelected();return} const {error}=await supa.from('canvass_status').delete().eq('parcel_id',id);if(error){toast(error.message);return} state.delete(id);refresh();openSelected();}
function popup(f){const p=f.properties,s=statusFor(p.ParcelID);let label=p.display||p.ParcelID;return `<b>${label}</b><br>Parcel: ${p.ParcelID}${p.PID?'<br>PID: '+p.PID:''}<br><span style="color:#6b7280">${s.status==='visited'?'Visited by '+s.user:s.status==='claimed'?'Claimed by '+s.user:'Not yet visited'}</span><div class="popup-actions"><button onclick="selectParcel('${p.ParcelID}')">Open</button></div>`}
window.selectParcel=id=>{const f=features.find(x=>x.properties.ParcelID===id);if(f){selected=f;openSelected();map.fitBounds(L.geoJSON(f).getBounds(),{maxZoom:18})}};
function openSelected(){if(!selected)return;const p=selected.properties,s=statusFor(p.ParcelID);$('parcelTitle').textContent=p.display||p.ParcelID;$('parcelInfo').innerHTML=`<div><b>Parcel ID:</b> ${p.ParcelID}</div>${p.PID?`<div><b>PID:</b> ${p.PID}</div>`:''}${p.PlanNumber?`<div><b>Plan:</b> ${p.PlanNumber}</div>`:''}`;$('currentStatus').textContent=s.status==='visited'?`Visited by ${s.user}. Updated ${new Date(s.updated_at).toLocaleString()}`:s.status==='claimed'?`Claimed by ${s.user}. Updated ${new Date(s.updated_at).toLocaleString()}`:'Not yet visited';$('panel').classList.remove('hidden')}
async function connect(url,key){supa=window.supabase.createClient(url,key); const auth=await supa.auth.signInAnonymously(); if(auth.error) throw auth.error; const {data,error}=await supa.from('canvass_status').select('*'); if(error)throw error; data.forEach(r=>state.set(r.parcel_id,r)); channel=supa.channel('canvass-status').on('postgres_changes',{event:'*',schema:'public',table:'canvass_status'},payload=>{if(payload.eventType==='DELETE')state.delete(payload.old.parcel_id);else state.set(payload.new.parcel_id,payload.new);refresh();if(selected)openSelected()}).subscribe();}
async function init(){const geo=await fetch(DATA_URL).then(r=>r.json());features=geo.features; map=L.map('map',{zoomControl:true}).setView([48.55,-123.55],11);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:20,attribution:'© OpenStreetMap contributors'}).addTo(map);boundaryLayer=L.geoJSON(await fetch(BOUNDARY_URL).then(r=>r.json()),{style:{color:'#111827',weight:3,fill:false}}).addTo(map);parcelsLayer=L.geoJSON(geo,{style:styleFeature,onEachFeature:(f,l)=>{l.bindPopup(popup(f));l.on('click',()=>{selected=f;openSelected()})}}).addTo(map);map.fitBounds(parcelsLayer.getBounds());updateStats();}
$('saveSetup').onclick=async()=>{const u=$('sbUrl').value.trim(),k=$('sbKey').value.trim();if(!u||!k){toast('Enter both Supabase values');return}try{await connect(u,k);localStorage.setItem('sb_url',u);localStorage.setItem('sb_key',k);$('setup').classList.add('hidden');toast('Collaborative mode connected')}catch(e){toast('Connection failed: '+e.message)}};
$('demoMode').onclick=()=>{demo=true;loadDemo();$('setup').classList.add('hidden');refresh();toast('Demo mode: changes stay on this device')};
$('closePanel').onclick=()=>{$('panel').classList.add('hidden');selected=null};$('claim').onclick=()=>selected&&setStatus(selected.properties.ParcelID,'claimed');$('visit').onclick=()=>selected&&setStatus(selected.properties.ParcelID,'visited');$('release').onclick=()=>selected&&release(selected.properties.ParcelID);
$('locate').onclick=()=>map.locate({setView:true,maxZoom:17});$('me').onclick=()=>{const n=user();if(!n){toast('Enter your name on a parcel first');return} const ids=[...state.entries()].filter(([id,s])=>s.user===n).map(([id])=>id);if(!ids.length){toast('No parcels marked by '+n);return}const layers=ids.map(id=>features.find(f=>f.properties.ParcelID===id)).filter(Boolean).map(f=>L.geoJSON(f));const group=L.featureGroup(layers);map.fitBounds(group.getBounds(),{padding:[20,20]})};
$('search').addEventListener('input',e=>{const q=e.target.value.toLowerCase().trim();if(!q)return;if(q.length<3)return;const f=features.find(x=>(x.properties.search||'').includes(q));if(f)selectParcel(f.properties.ParcelID)});
(async()=>{await init();const u=localStorage.getItem('sb_url'),k=localStorage.getItem('sb_key');if(u&&k){try{await connect(u,k);$('setup').classList.add('hidden');toast('Connected to shared map')}catch{}}})();